Migrate filter_map to use v0.14 API
fluent-plugins-nursery/fluent-plugin-map pull request #18
Opened 2017-03-14 09:55 UTC by cosmo0920

2017-03-15 03:24 UTC, okkez requested changes
We can drop old Fluentd support v0.12 or earlier.
When we start using Fluentd v0.14 API.

2017-03-15 03:24 UTC, okkez commented on .travis.yml
> +      gemfile: gemfiles/fluentd_0_10.gemfile
Fluentd v0.14 API does not work with Fluentd v0.10.
So we can drop old Fluentd version support.

2017-03-15 03:24 UTC, okkez commented on .travis.yml
> +      gemfile: gemfiles/fluentd_0_12.gemfile
Fluentd v0.14 API does not work with Fluentd v0.12.
So we can drop old Fluentd version support.

2017-03-15 03:24 UTC, okkez commented on lib/fluent/plugin/map_support.rb
> +      if defined?(Fluent::Plugin::Filter) and plugin.is_a?(Fluent::Plugin::Filter)
`plugin.is_a?(Fluent::Plugin::Filter)` is enough.
Because we can drop old Fluentd (v0.12 or earlier) support.

2017-03-15 03:24 UTC, okkez commented on test/helper.rb
> +require "fluent/plugin/filter_map" if defined?(Fluent::Plugin::Filter)
We can remove `if defined?(Fluent::Plugin::Filter)`.

2017-03-15 03:24 UTC, okkez commented on test/plugin/test_filter_map.rb
> +    omit "Use Fluentd v0.14 or later" unless defined?(Fluent::Plugin::Filter)
We can run these test always.

2017-03-15 03:24 UTC, okkez commented on test/plugin/test_filter_map.rb
> +begin
We can use require these libraries without this begin-rescue block.

2017-03-15 05:10 UTC, cosmo0920 commented on .travis.yml
> +      gemfile: gemfiles/fluentd_0_10.gemfile
In this PR, I didn't use v0.14 API in out_map.
Should we migrate it same as filter_map?

2017-03-15 05:10 UTC, cosmo0920 commented on lib/fluent/plugin/map_support.rb
> +      if defined?(Fluent::Plugin::Filter) and plugin.is_a?(Fluent::Plugin::Filter)
ditto.

2017-03-15 05:10 UTC, cosmo0920 commented on test/helper.rb
> +require "fluent/plugin/filter_map" if defined?(Fluent::Plugin::Filter)
I don't want to remove out_map right now.
Should we remove out_map in this plugin?

2017-03-15 06:40 UTC, okkez commented on .travis.yml
> +      gemfile: gemfiles/fluentd_0_10.gemfile
Yes. We should migrate out_map, too :cake:

2017-03-15 06:42 UTC, okkez commented on test/helper.rb
> +require "fluent/plugin/filter_map" if defined?(Fluent::Plugin::Filter)
No. Keep out_map plugin for now.
`Fluent::Plugin::Filter` is defined always with Fluentd v0.14.

2017-03-15 06:43 UTC, cosmo0920 commented on .travis.yml
> +      gemfile: gemfiles/fluentd_0_10.gemfile
Hmm, I don't want to migrate out_map to use v0.14.
Because out_map can replace with filter_map and label feature.

2017-03-15 09:34 UTC, cosmo0920 commented
With @okkez and I F2F discussion, we decide to migrate both of map plugins instead of only doing filter_map.

2017-03-16 02:06 UTC, okkez commented on .travis.yml
> +matrix:
How about following?

```
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
gemfile:
  - gemfiles/fluentd_0_14.gemfile
  - Gemfile
```

2017-03-16 02:32 UTC, okkez approved these changes

2017-03-16 02:36 UTC, cosmo0920 commented
I'll merge this PR after finishing CI.

2017-03-16 02:44 UTC, merged